/** Embedded country set — name, capital, emoji flag. No network needed. */
const COUNTRIES = [
  { name: "France", capital: "Paris", flag: "🇫🇷" },
  { name: "Japan", capital: "Tokyo", flag: "🇯🇵" },
  { name: "Brazil", capital: "Brasília", flag: "🇧🇷" },
  { name: "India", capital: "New Delhi", flag: "🇮🇳" },
  { name: "Egypt", capital: "Cairo", flag: "🇪🇬" },
  { name: "Canada", capital: "Ottawa", flag: "🇨🇦" },
  { name: "Australia", capital: "Canberra", flag: "🇦🇺" },
  { name: "Italy", capital: "Rome", flag: "🇮🇹" },
  { name: "Germany", capital: "Berlin", flag: "🇩🇪" },
  { name: "Spain", capital: "Madrid", flag: "🇪🇸" },
  { name: "Mexico", capital: "Mexico City", flag: "🇲🇽" },
  { name: "South Korea", capital: "Seoul", flag: "🇰🇷" },
  { name: "United Kingdom", capital: "London", flag: "🇬🇧" },
  { name: "United States", capital: "Washington, D.C.", flag: "🇺🇸" },
  { name: "China", capital: "Beijing", flag: "🇨🇳" },
  { name: "Argentina", capital: "Buenos Aires", flag: "🇦🇷" },
  { name: "South Africa", capital: "Pretoria", flag: "🇿🇦" },
  { name: "Turkey", capital: "Ankara", flag: "🇹🇷" },
  { name: "Greece", capital: "Athens", flag: "🇬🇷" },
  { name: "Sweden", capital: "Stockholm", flag: "🇸🇪" },
  { name: "Norway", capital: "Oslo", flag: "🇳🇴" },
  { name: "Netherlands", capital: "Amsterdam", flag: "🇳🇱" },
  { name: "Portugal", capital: "Lisbon", flag: "🇵🇹" },
  { name: "Poland", capital: "Warsaw", flag: "🇵🇱" },
  { name: "Ireland", capital: "Dublin", flag: "🇮🇪" },
  { name: "Switzerland", capital: "Bern", flag: "🇨🇭" },
  { name: "Austria", capital: "Vienna", flag: "🇦🇹" },
  { name: "Belgium", capital: "Brussels", flag: "🇧🇪" },
  { name: "Denmark", capital: "Copenhagen", flag: "🇩🇰" },
  { name: "Finland", capital: "Helsinki", flag: "🇫🇮" },
  { name: "New Zealand", capital: "Wellington", flag: "🇳🇿" },
  { name: "Thailand", capital: "Bangkok", flag: "🇹🇭" },
  { name: "Vietnam", capital: "Hanoi", flag: "🇻🇳" },
  { name: "Indonesia", capital: "Jakarta", flag: "🇮🇩" },
  { name: "Malaysia", capital: "Kuala Lumpur", flag: "🇲🇾" },
  { name: "Philippines", capital: "Manila", flag: "🇵🇭" },
  { name: "Saudi Arabia", capital: "Riyadh", flag: "🇸🇦" },
  { name: "United Arab Emirates", capital: "Abu Dhabi", flag: "🇦🇪" },
  { name: "Kenya", capital: "Nairobi", flag: "🇰🇪" },
  { name: "Nigeria", capital: "Abuja", flag: "🇳🇬" },
  { name: "Morocco", capital: "Rabat", flag: "🇲🇦" },
  { name: "Chile", capital: "Santiago", flag: "🇨🇱" },
  { name: "Colombia", capital: "Bogotá", flag: "🇨🇴" },
  { name: "Peru", capital: "Lima", flag: "🇵🇪" },
  { name: "Russia", capital: "Moscow", flag: "🇷🇺" },
  { name: "Ukraine", capital: "Kyiv", flag: "🇺🇦" },
  { name: "Czech Republic", capital: "Prague", flag: "🇨🇿" },
  { name: "Hungary", capital: "Budapest", flag: "🇭🇺" },
  { name: "Israel", capital: "Jerusalem", flag: "🇮🇱" },
  { name: "Singapore", capital: "Singapore", flag: "🇸🇬" },
  { name: "Iceland", capital: "Reykjavík", flag: "🇮🇸" },
  { name: "Cuba", capital: "Havana", flag: "🇨🇺" },
  { name: "Jamaica", capital: "Kingston", flag: "🇯🇲" },
  { name: "Pakistan", capital: "Islamabad", flag: "🇵🇰" },
  { name: "Bangladesh", capital: "Dhaka", flag: "🇧🇩" },
];
